// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7dRzWwyvCBmGGkrmX9HEL4T3me5-QSQ',
    appId: '1:218379071488:android:c5822d02154431e0f068e5',
    messagingSenderId: '218379071488',
    projectId: 'flutter-chat-app-7790f',
    storageBucket: 'flutter-chat-app-7790f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCku3qiURWYMWOzihexOn_3ayV8MtMNFtY',
    appId: '1:218379071488:ios:26a8c62d805d3f50f068e5',
    messagingSenderId: '218379071488',
    projectId: 'flutter-chat-app-7790f',
    storageBucket: 'flutter-chat-app-7790f.appspot.com',
    iosClientId: '218379071488-vfa0gjq4fo3012t50qf9ho78u5vol5si.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCku3qiURWYMWOzihexOn_3ayV8MtMNFtY',
    appId: '1:218379071488:ios:c93d90d3d8a45159f068e5',
    messagingSenderId: '218379071488',
    projectId: 'flutter-chat-app-7790f',
    storageBucket: 'flutter-chat-app-7790f.appspot.com',
    iosClientId: '218379071488-e4nd4eieo0lrjnd3g17rtc241h3pgcpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
